[package]
name = "hls_player"
version = "0.1.0"
edition = "2018"


[dependencies]
rodio = { git = "https://github.com/RustAudio/rodio.git", default-features = false, features = ["symphonia-aac"] }
mpeg2ts = "0.1"
hls_m3u8 = "0.4"
