[package]
name = "media"
version = "0.3.1"
authors = ["Rrogntudju"]
edition = "2024"

[dependencies]
serde = { version ="1", features = ["derive"] }
serde_json = "1"
reqwest = "0.12"
anyhow = "1"

[dev-dependencies]
tokio = {version = "1", features = ["macros"]}
