[package]
name = "media"
version = "0.3.0"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
serde = { version ="1", features = ["derive"] }
serde_json = "1"
reqwest = "0.11"
anyhow = "1"

[dev-dependencies]
tokio = {version = "1", features = ["macros"]}
