[package]
name = "hls2file"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
hls_handler = {path = "../hls_handler"}
gratte = {path = "../gratte"}
reqwest = "0.11"
serde_json = "1"
tokio = {version = "1", features = ["macros"]}

