[package]
name = "hls2file"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
hls_handler = {path = "../hls_handler"}
gratte = {path = "../gratte"}
minreq = { version = "2", features = ["https", "json-using-serde"] }

