[package]
name = "hls2file"
version = "0.4.0"
authors = ["Rrogntudju"]
edition = "2024"

[dependencies]
hls_handler = {path = "../hls_handler"}
media = {path = "../media"}
reqwest = "0.12"
serde_json = "1"
tokio = {version = "1", features = ["rt-multi-thread", "macros", "fs"]}

