[package]
name = "hls2file"
version = "0.2.1"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
hls_handler = {path = "../hls_handler"}
media = {path = "../media"}
reqwest = "0.11"
serde_json = "1"
tokio = {version = "1", features = ["macros"]}

