[package]
name = "play"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
rodio = { git = "https://github.com/RustAudio/rodio.git", default-features = false, features = ["symphonia-aac"] }

