[package]
name = "hls_play_live"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2024"

[dependencies]
hls_player = {path = "../hls_player"}
reqwest = "0.12"
serde_json = "1"
tokio = {version = "1", features = ["rt-multi-thread", "macros"]}

