[package]
name = "hls_play_od"
version = "0.2.1"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
hls_player = {path = "../hls_player"}
media = {path = "../media"}
reqwest = "0.11"
serde_json = "1"
tokio = {version = "1", features = ["rt-multi-thread", "macros"]}

