[package]
name = "odieux"
version = "0.4.3"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
axum = {version = "0.7", default-features = false}
tokio = { version = "1", features = ["rt", "macros"] }
anyhow = "1"
server = {path = "../server"}


