[package]
name = "odieux"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
warp = "0.3" 
tokio = { version = "1.12", features = ["rt", "macros"] }
anyhow = "1"
lazy_static = "1.4"
hls_player = {path = "../hls_player"}

