[package]
name = "odieux"
version = "0.1.1"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["rt", "macros"] }
anyhow = "1"
server = {path = "../server"}


