[package]
name = "odieux"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
warp = "0.3" 
tokio = { version = "1", features = ["rt", "macros"] }
anyhow = "1"
server = {path = "../server"}


