[package]
name = "decrypt_aes128"
authors = ["https://stackoverflow.com/users/11696053/universe-chen", "Rrogntudju"]
version = "0.1.0"
edition = "2018"

[dependencies]
aes = "0.7"
block-modes = "0.8"
anyhow = "1"

