[package]
name = "hls_play"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
hls_player = {path = "../hls_player"}
gratte = {path = "../gratte"}
minreq = { version = "2", features = ["https", "json-using-serde"] }
serde_json = "1"

