[package]
name = "hls_handler"
version = "0.1.0"
edition = "2018"


[dependencies]
mpeg2ts = "0.1"
hls_m3u8 = "0.4"
trackable = "1.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
url = { version = "2", features = ["serde"] }
url_serde = "0.2"