[package]
name = "hls_handler"
version = "0.2.0"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
mpeg2ts = "0.2"
hls_m3u8 = "0.4"
url = "2"
anyhow = "1"
libaes = "0.6"
reqwest = "0.11"
tokio = "1"
