[package]
name = "hls_handler"
version = "0.2.0"
authors = ["Rrogntudju"]
edition = "2024"

[dependencies]
mpeg2ts = "0.3"
hls_m3u8 = "0.4"
url = "2"
anyhow = "1"
libaes = "0.7"
reqwest = "0.12"
tokio = "1"
